spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: ${INITIALIZE_DB}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: ${SCHEMA_DB}
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: ${JWT_EXPIRATION}
  emailUsername: ${EMAIL_USERNAME}
  emailPassword: ${EMAIL_PASSWORD}
  hostUrl: ${HOST_URL}
  stripeApiKey: ${STRIPE_API_KEY}
server:
  error:
    include-message: always
    include-stacktrace: never
